./undeadServer army army.mem 8191
./undeadServer actor actor.mem 1023
./undeadServer city city.mem 79999
./undeadServer club club.mem 2000
./undeadServer maptown maptown.mem 43
./undeadServer mapres mapres.mem 99999
./undeadServer ctown clubtown.mem 4095
./undeadServer cstore clubstore.mem 2043
./undeadServer cjet clubjet.mem 4095
./undeadServer cres clubres.mem 2043
./undeadServer kcity kingcity.mem 1
./undeadServer ktower kingtower.mem 4