--client_struct_auto.lua

CMDS_BASE = 0;
CMDC_BASE = 0;

CMDS_LOGIN = CMDS_BASE+1;
CMDS_LIST = CMDS_BASE+2;
CMDS_CREATE = CMDS_BASE+3;
CMDS_ENTERINFO = CMDS_BASE+4;
CMDS_DELETE = CMDS_BASE+5;
CMDS_HEART = CMDS_BASE+6;
CMDS_NOTIFY = CMDS_BASE+7;
CMDS_ACTORINFO = CMDS_BASE+8;
CMDS_ITEMUSE = CMDS_BASE+9;
CMDS_ITEMPUT = CMDS_BASE+10;
CMDS_ITEMSETTLE = CMDS_BASE+11;
CMDS_LOSTITEM = CMDS_BASE+12;
CMDS_GETITEM = CMDS_BASE+13;
CMDS_ITEMLIST = CMDS_BASE+14;
CMDS_ITEMINFO = CMDS_BASE+15;
CMDS_ADDMAPUNIT = CMDS_BASE+16;
CMDS_DELMAPUNIT = CMDS_BASE+17;
CMDS_UPDATEMAPUNIT = CMDS_BASE+18;
CMDS_MAPUNITSINGLE = CMDS_BASE+19;
CMDS_WORLDMAPINFO = CMDS_BASE+20;
CMDS_MAPUNITCORRDINATE = CMDS_BASE+21;
CMDS_ADDMARCHROUTE = CMDS_BASE+22;
CMDS_DELMARCHROUTE = CMDS_BASE+23;
CMDS_AWARDINFOLIST = CMDS_BASE+24;
CMDS_EXPERIENCE = CMDS_BASE+25;
CMDS_BODY = CMDS_BASE+26;

CMDC_LOGIN = CMDC_BASE+1;
CMDC_CREATE = CMDC_BASE+2;
CMDC_LIST = CMDC_BASE+3;
CMDC_ENTERGAME = CMDC_BASE+4;
CMDC_DELETE = CMDC_BASE+5;
CMDC_HEART = CMDC_BASE+6;
CMDC_GMCMD = CMDC_BASE+7;
CMDC_ASKINFO = CMDC_BASE+9;

