//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_AnimationTimelineStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.AnimationTimelineState), typeof(DragonBones.TimelineState<DragonBones.AnimationFrameData,DragonBones.AnimationData>));
		L.RegFunction("Update", Update);
		L.RegFunction("setCurrentTime", setCurrentTime);
		L.RegFunction("New", _CreateDragonBones_AnimationTimelineState);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDragonBones_AnimationTimelineState(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DragonBones.AnimationTimelineState obj = new DragonBones.AnimationTimelineState();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DragonBones.AnimationTimelineState.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DragonBones.AnimationTimelineState obj = (DragonBones.AnimationTimelineState)ToLua.CheckObject(L, 1, typeof(DragonBones.AnimationTimelineState));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setCurrentTime(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DragonBones.AnimationTimelineState obj = (DragonBones.AnimationTimelineState)ToLua.CheckObject(L, 1, typeof(DragonBones.AnimationTimelineState));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.setCurrentTime(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

