//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_TimelineData_DragonBones_AnimationFrameDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.TimelineData<DragonBones.AnimationFrameData>), typeof(DragonBones.BaseObject), "TimelineData_DragonBones_AnimationFrameData");
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("scale", get_scale, set_scale);
		L.RegVar("offset", get_offset, set_offset);
		L.RegVar("frames", get_frames, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_scale(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.TimelineData<DragonBones.AnimationFrameData> obj = (DragonBones.TimelineData<DragonBones.AnimationFrameData>)o;
			float ret = obj.scale;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index scale on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_offset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.TimelineData<DragonBones.AnimationFrameData> obj = (DragonBones.TimelineData<DragonBones.AnimationFrameData>)o;
			float ret = obj.offset;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index offset on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_frames(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.TimelineData<DragonBones.AnimationFrameData> obj = (DragonBones.TimelineData<DragonBones.AnimationFrameData>)o;
			System.Collections.Generic.List<DragonBones.AnimationFrameData> ret = obj.frames;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index frames on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_scale(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.TimelineData<DragonBones.AnimationFrameData> obj = (DragonBones.TimelineData<DragonBones.AnimationFrameData>)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.scale = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index scale on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_offset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.TimelineData<DragonBones.AnimationFrameData> obj = (DragonBones.TimelineData<DragonBones.AnimationFrameData>)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.offset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index offset on a nil value" : e.Message);
		}
	}
}

