//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_BoneTimelineStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.BoneTimelineState), typeof(DragonBones.TweenTimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>));
		L.RegFunction("_init", _init);
		L.RegFunction("FadeOut", FadeOut);
		L.RegFunction("Update", Update);
		L.RegFunction("New", _CreateDragonBones_BoneTimelineState);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("bone", get_bone, set_bone);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDragonBones_BoneTimelineState(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DragonBones.BoneTimelineState obj = new DragonBones.BoneTimelineState();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DragonBones.BoneTimelineState.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			DragonBones.BoneTimelineState obj = (DragonBones.BoneTimelineState)ToLua.CheckObject(L, 1, typeof(DragonBones.BoneTimelineState));
			DragonBones.Armature arg0 = (DragonBones.Armature)ToLua.CheckObject(L, 2, typeof(DragonBones.Armature));
			DragonBones.AnimationState arg1 = (DragonBones.AnimationState)ToLua.CheckObject(L, 3, typeof(DragonBones.AnimationState));
			DragonBones.BoneTimelineData arg2 = (DragonBones.BoneTimelineData)ToLua.CheckObject(L, 4, typeof(DragonBones.BoneTimelineData));
			obj._init(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FadeOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DragonBones.BoneTimelineState obj = (DragonBones.BoneTimelineState)ToLua.CheckObject(L, 1, typeof(DragonBones.BoneTimelineState));
			obj.FadeOut();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DragonBones.BoneTimelineState obj = (DragonBones.BoneTimelineState)ToLua.CheckObject(L, 1, typeof(DragonBones.BoneTimelineState));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_bone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.BoneTimelineState obj = (DragonBones.BoneTimelineState)o;
			DragonBones.Bone ret = obj.bone;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index bone on a nil value" : e.Message);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_bone(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DragonBones.BoneTimelineState obj = (DragonBones.BoneTimelineState)o;
			DragonBones.Bone arg0 = (DragonBones.Bone)ToLua.CheckObject(L, 2, typeof(DragonBones.Bone));
			obj.bone = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o == null ? "attempt to index bone on a nil value" : e.Message);
		}
	}
}

