//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_DragonBonesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.DragonBones), typeof(System.Object));
		L.RegFunction("Assert", Assert);
		L.RegFunction("New", _CreateDragonBones_DragonBones);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegConstant("PI", 3.14159274101257);
		L.RegConstant("PI_D", 6.28318548202515);
		L.RegConstant("PI_H", 1.57079637050629);
		L.RegConstant("PI_Q", 0.785398185253143);
		L.RegConstant("ANGLE_TO_RADIAN", 0.0174532923847437);
		L.RegConstant("RADIAN_TO_ANGLE", 57.2957763671875);
		L.RegConstant("SECOND_TO_MILLISECOND", 1000);
		L.RegConstant("NO_TWEEN", 100);
		L.RegVar("VSESION", get_VSESION, null);
		L.RegVar("ARGUMENT_ERROR", get_ARGUMENT_ERROR, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateDragonBones_DragonBones(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				DragonBones.DragonBones obj = new DragonBones.DragonBones();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: DragonBones.DragonBones.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Assert(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 1);
			string arg1 = ToLua.CheckString(L, 2);
			DragonBones.DragonBones.Assert(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_VSESION(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.DragonBones.VSESION);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ARGUMENT_ERROR(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, DragonBones.DragonBones.ARGUMENT_ERROR);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

