//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DragonBones_TimelineState_DragonBones_BoneFrameData_DragonBones_BoneTimelineDataWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>), typeof(DragonBones.BaseObject), "TimelineState_DragonBones_BoneFrameData_DragonBones_BoneTimelineData");
		L.RegFunction("_init", _init);
		L.RegFunction("FadeOut", FadeOut);
		L.RegFunction("Update", Update);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData> obj = (DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>)ToLua.CheckObject(L, 1, typeof(DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>));
			DragonBones.Armature arg0 = (DragonBones.Armature)ToLua.CheckObject(L, 2, typeof(DragonBones.Armature));
			DragonBones.AnimationState arg1 = (DragonBones.AnimationState)ToLua.CheckObject(L, 3, typeof(DragonBones.AnimationState));
			DragonBones.BoneTimelineData arg2 = (DragonBones.BoneTimelineData)ToLua.CheckObject(L, 4, typeof(DragonBones.BoneTimelineData));
			obj._init(arg0, arg1, arg2);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int FadeOut(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData> obj = (DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>)ToLua.CheckObject(L, 1, typeof(DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>));
			obj.FadeOut();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Update(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData> obj = (DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>)ToLua.CheckObject(L, 1, typeof(DragonBones.TimelineState<DragonBones.BoneFrameData,DragonBones.BoneTimelineData>));
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.Update(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

