//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class OpenUDIDPhone_OpenUDIDWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("OpenUDID");
		L.RegFunction("valueWithError", valueWithError);
		L.RegFunction("GetCorpUDID", GetCorpUDID);
		L.RegVar("CorpIdentifier", get_CorpIdentifier, set_CorpIdentifier);
		L.RegVar("MacAddress", get_MacAddress, null);
		L.RegVar("value", get_value, null);
		L.RegVar("CorpValue", get_CorpValue, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int valueWithError(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			OpenUDIDPhone.OpenUDID.OpenUDIDErrors arg0;
			string o = OpenUDIDPhone.OpenUDID.valueWithError(out arg0);
			LuaDLL.lua_pushstring(L, o);
			ToLua.Push(L, arg0);
			return 2;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetCorpUDID(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = OpenUDIDPhone.OpenUDID.GetCorpUDID(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CorpIdentifier(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, OpenUDIDPhone.OpenUDID.CorpIdentifier);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MacAddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, OpenUDIDPhone.OpenUDID.MacAddress);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_value(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, OpenUDIDPhone.OpenUDID.value);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CorpValue(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, OpenUDIDPhone.OpenUDID.CorpValue);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_CorpIdentifier(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			OpenUDIDPhone.OpenUDID.CorpIdentifier = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

