CREATE TABLE `city` (
  `cityid` int(11) NOT NULL DEFAULT '0' COMMENT '城池ID',
  `actorid` int(11) NOT NULL DEFAULT '0' COMMENT '角色ID',
  `name` varbinary(22) NOT NULL DEFAULT '' COMMENT '名称',
  `type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '城池类型',
  `shape` tinyint(4) NOT NULL DEFAULT '0' COMMENT '城池形象',
  `headid` int(11) NOT NULL DEFAULT '0' COMMENT '默认头像',
  `country` varbinary(3) NOT NULL DEFAULT '' COMMENT '选择的国家',
  `ipcountry` varbinary(3) NOT NULL DEFAULT '' COMMENT 'IP地址所在国家',
  `language` tinyint(4) NOT NULL DEFAULT '0' COMMENT '选择语言',
  `os` tinyint(4) NOT NULL DEFAULT '0' COMMENT '系统1ios 2android 3win',
  `platid` tinyint(4) NOT NULL DEFAULT '0' COMMENT '平台',
  `createtime` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `lastlogin` int(11) NOT NULL DEFAULT '0' COMMENT '上次登陆时间',
  `lastlogout` int(11) NOT NULL DEFAULT '0' COMMENT '上次登出时间',
  `state` tinyint(4) NOT NULL DEFAULT '0' COMMENT '城池当前状态',
  `posx` smallint(6) NOT NULL DEFAULT '0' COMMENT '位置',
  `posy` smallint(6) NOT NULL DEFAULT '0' COMMENT '位置',
  `sflag` int(11) NOT NULL DEFAULT '0' COMMENT '标志位',
  `level` tinyint(4) NOT NULL DEFAULT '0' COMMENT '等级',
  `vipexp` int(11) NOT NULL DEFAULT '0' COMMENT 'VIP经验',
  `politics` smallint(6) NOT NULL DEFAULT '0' COMMENT '民生设施(一级属性)',
  `politics_exp` int(11) NOT NULL DEFAULT '0' COMMENT '民生设施经验',
  `farm` smallint(6) NOT NULL DEFAULT '0' COMMENT '农业设施(一级属性)',
  `farm_exp` int(11) NOT NULL DEFAULT '0' COMMENT '农业设施经验',
  `business` smallint(6) NOT NULL DEFAULT '0' COMMENT '商业设施(一级属性)',
  `business_exp` int(11) NOT NULL DEFAULT '0' COMMENT '商业设施经验',
  `military` smallint(6) NOT NULL DEFAULT '0' COMMENT '军事设施(一级属性)',
  `military_exp` int(11) NOT NULL DEFAULT '0' COMMENT '军事设施经验',
  `people` int(11) NOT NULL DEFAULT '0' COMMENT '人口(二级属性)',
  `food` int(11) NOT NULL DEFAULT '0' COMMENT '食物(二级属性)',
  `money` int(11) NOT NULL DEFAULT '0' COMMENT '金钱(二级属性)',
  `soldiers` int(11) NOT NULL DEFAULT '0' COMMENT '兵员(二级属性)',
  PRIMARY KEY (`cityid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
